print("""""")
print("""\"""")
print("""\\""")
print(""" ""\" """)
print(""" ""\' """)
print(""" ''' """)
print(b""" """)
print(rb""" """)
print(br""" """)
print(RB""" """)
print(RB""" \" """)
print(B""" \" """)
print(B""" \" """)
print(B""" \\" """)
print(B""" \\\" """)
print(B""" \\\\" """)
print(B""" \\\\"\\\\' """)
print(B""" \\\\"\\\' """)
print(B""" \\\\"\\\" """)
x=15
print(f'{x}')
print(f'ooo {x}oooo')
y = 20
print(f'{x}{y}')
print(f'''{x} {y}''')
z = 30
print(f'x{x}{y} {z} {x}')
print('a' + 'b')
print('\x62')
print('\u0062')
print(b'abcd')
print(b'\x60')
print(b'a' + b'b')
